### ISSUE TITLE
Search and sort data

### ISSUE THREAD

**Issue by przemgk** [przemgk/Frontend-Mentor-CH15#15]
**Tasks to do:**
- [x] Search country when you typing
- [x] Sort country by region
- [x] Add search no results info
