### ISSUE TITLE
Components refactoring

### ISSUE THREAD

**Issue by przemgk** [przemgk/Frontend-Mentor-CH15#16]
**Tasks to do:**
- [x] Optimize fetching data from API
- [x] Delete preloader where it is unnecessary

**Atoms to refactoring:**
- [x] Button
- [x] Dropdown

**Molecules to refactoring:**
- [x] Card
- [x] DataSet

**Organisms to refactoring:**
- [x] FilterBar

**Views to refactoring:**
- [x] 404 view
- [x] Connection-failed view
